# Generated by Django 4.0.6 on 2022-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_apartment_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
