# Generated by Django 4.0.6 on 2022-07-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_adults_reservation_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_end',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_started',
            field=models.DateField(unique=True),
        ),
    ]
